### ISSUE TITLE
Cannot generate default format documentation

### ISSUE THREAD

**Issue by MarcSteven** [SwiftDocOrg/swift-doc#88] opened 2020-04-18 04:17 UTC
Thank for your sharing @mattt , but I just tried and then cannot generate the default format documentation

**Comment by mattt** [comment] 2020-04-19 23:03
@MarcSteven This isn't very much information to go on, but if I had to guess, this sounds like a duplicate of #70.

As I wrote in that thread:

> If documentation for your own classes aren't showing up, it's most likely because they aren't declared with `public` or `open` modifiers. By default, declarations have an implicit `internal` access level, and those aren't currently emitted by `swift-doc`.
> 
> For example, if you have a view controller, like:
> 
> ```swift
> /// Documentation for MyViewController
> class MyViewController: UIViewController { ... }
> ```
> 
> You should make add a `public` access modifier:
> 
> ```swift
> /// Documentation for MyViewController
> public class MyViewController: UIViewController { ... }
> ```

**Comment by MarcSteven** [comment] 2020-04-20 00:26
Hi @mattt  It has no relationship with it, I declared with public or open, but it can generate the default format, but it can generate the documentation of HTML.

**Comment by mattt** [comment] 2020-04-20 17:26
@MarcSteven Again, this isn't really enough information to go on. Without knowing what version of Swift you're using, what version of `swift-doc` you have installed, what command you used to generate, or what code you're trying to generate documentation for, all I can do is guess at the problem.

So here's another guess: Have you tried reinstalling the latest version of `swift-doc` or running from the latest `master`?

**Comment by MarcSteven** [comment] 2020-04-21 02:58
I used the latest swift and latest swift-doc and then it cannot generate the default format, and then I tried to reinstall and then cannot fix the issue.

**Comment by mattt** [comment] 2020-04-21 15:16
@MarcSteven Sorry, but this isn't very helpful. Please provide the information requested, or I won't be able to resolve your issue.

**Comment by MarcSteven** [comment] 2020-04-22 12:46
The error as below:
`2020-04-22 20:45:29.089 xcodebuild[2738:37257] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2020-04-22 20:45:29.090 xcodebuild[2738:37257] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2020-04-22 20:45:29.090 xcodebuild[2738:37257] Failed to load plugin at: /Users/MarcZhao/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
2020-04-22 20:45:29.091 xcodebuild[2738:37257] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/JSPatchX.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2020-04-22 20:45:29.093 xcodebuild[2738:37257] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CleanHeaders.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2020-04-22 20:45:29.095 xcodebuild[2738:37257] [MT] PluginLoading: Required plug-in compatibility UUID C80A9C11-3902-4885-944E-A035869BA910 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs`

**Comment by mattt** [comment] 2020-04-22 19:12
These are `xcodebuild` errors related to... failure to load missing Xcode plugins (?). I don't see how this relates to `swift-doc`.

**Comment by MarcSteven** [comment] 2020-04-23 02:02
When I executed the command, it showed the error like that...

**Comment by kean** [comment] 2020-04-27 21:55
Might be related. I compiled the [latest](https://github.com/SwiftDocOrg/swift-doc/commits/master) version from master. Running `generate` produces nothing for me unless you specify an output folder.

**Comment by mattt** [comment] 2020-05-06 19:18
Without sufficient information to reproduce this problem, there's nothing else I'm able to do. Closing.

**Closed by mattt** 2020-05-06 19:18 UTC
Labels: question
