### ISSUE TITLE
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib after homebrew install

### ISSUE THREAD

**Issue by MattKiazyk** [SwiftDocOrg/swift-doc#197] opened 2020-10-02 16:22 UTC
While related to #60 I'm just simply trying to run generate on the command line after install, so I thought I'd create a new ticket. 

Steps:
- Xcode 12.0.1 or 12.0
- Installed beta-5 via homebrew `brew install swiftdocorg/formulae/swift-doc`
- ran `swift doc generate -f html ...` via command line 

received:
```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /usr/local/bin/swift-doc
  Reason: image not found
```

I did not receive this on beta-4 or earlier, granted I had been building it locally when I was making changes, so perhaps that stopped it from happening. 

The workaround is to make sure I have my Xcode 12 named `Xcode.app`. and not `Xcode-12.0.1`. Once that occurs, and I set my command tools to that - it does not receive that error (albeit getting the #196 issue)

**Comment by MaxDesiatov** [comment] 2020-10-04 12:43
+1 here, also fails for me `swift-doc --version`

**Comment by MaxDesiatov** [comment] 2020-10-04 12:45
My Xcode path is `/Applications/Xcode-12.0.0-gm-seed.app`.

**Comment by MaxDesiatov** [comment] 2020-10-04 13:25
The underlying issue is [SR-9038](https://bugs.swift.org/browse/SR-9038) I guess. Ideally, we want to link all Swift Syntax components statically so that we don't have a dependency on a specific Xcode version.

**Comment by MaxDesiatov** [comment] 2020-10-05 07:18
I was pointed to [this guide](https://github.com/apple/swift-syntax#embedding-swiftsyntax-in-an-application) in `README.md` of Swift Syntax. [We may also need to use `install_name_tool`](https://twitter.com/efron_megan/status/1312870238673805313?s=21) to update `@rpath`.

**Comment by mattt** [comment] 2020-10-07 10:56
This should be fixed by https://github.com/SwiftDocOrg/homebrew-formulae/commit/cb67508259b774d8b7cb34d4c1029bd2d0bd7285.

@MattKiazyk Could you please try reinstalling to verify this?

```terminal
$ brew uninstall swift-doc
$ brew untap swiftdocorg/formulae # in case you tapped our formula repo
$ brew install swiftdocorg/formulae/swift-doc
```

**Comment by MattKiazyk** [comment] 2020-10-07 13:31
I tried yesterday and it didn't work. Today It did work.

Although got an error when running `brew install swiftdocorg/formulae/swift-doc`
```
Error: No available formula or cask with the name "swiftdocorg/formulae/swift-doc".
```

but running again found it and installed it correctly. Thanks @mattt

**Comment by mattt** [comment] 2020-10-07 17:31
@MattKiazyk So glad to hear it! For posterity, here are updated commands to run for anyone else who may be getting that error message:

```terminal
$ brew uninstall swift-doc
$ brew untap swiftdocorg/formulae # in case you tapped our formula repo
$ brew tap swiftdocorg/formulae
$ brew install swift-doc
```

You may have also noticed that installation is now much faster thanks to the formula now having a bottle (e.g. pre-built binary).

Again, apologies for any inconvenience I may have caused by botching the distribution of this release. I've learned a lot more about Homebrew, and have taken this as an opportunity to improve the process going forward. Hoping to write up what I've learned in a blog post soon.

**Closed** 2020-10-07 17:31 UTC
Labels: bug
