### ISSUE TITLE
Invalid GitHub links/encoding for markdown wiki pages

### ISSUE THREAD

**Issue by twodayslate** [SwiftDocOrg/swift-doc#175] opened 2020-08-27 02:35 UTC
Example:
https://github.com/twodayslate/Swift-Big-Integer/wiki

A `max(_:​_:​)` page is created and is linked to in the Home.md but it does not redirect to the correct place and thus asks you to create a new page. https://github.com/twodayslate/Swift-Big-Integer/wiki/max(_:%E2%80%8B_:%E2%80%8B) instead of https://github.com/twodayslate/Swift-Big-Integer/wiki/max(_:_:)

Using beta4 GitHub Action

It should be `max%28_%3A_%3A%29`

I believe this might be a consequence of #149

**Comment by mattt** [comment] 2020-09-18 20:57
@twodayslate You are correct that this is caused by #149. Although that's since been reverted, it's still affecting the latest version. This will be fixed in the forthcoming release.

**Comment by mattt** [comment] 2020-09-25 12:29
Fixed by #167.

**Closed by mattt** 2020-09-25 12:29 UTC
Labels: bug
