### ISSUE TITLE
Code blocks are not indented

### ISSUE THREAD

**Issue by mbrandonw** [SwiftDocOrg/swift-doc#129] opened 2020-05-27 18:37 UTC
The following documentation:

https://github.com/pointfreeco/swift-composable-architecture/blob/6483439efdcf3d24b8ad6e9dea73fbe64c0531d2/Sources/ComposableArchitecture/Reducer.swift#L30-L46

Is rendered like so:

<details>
<summary>Expand</summary>
<img width="853" alt="image" src="https://user-images.githubusercontent.com/135203/83058541-618ef800-a00d-11ea-8019-178b7fc225af.png">
</details>

Dropping the `white-space: pre-line` [here](https://github.com/SwiftDocOrg/swift-doc/blob/a2013b64ffbcf91be45e6ecff9e88fdf8019a08d/Assets/css/all.css#L890) fixes it for me, but not sure if there are other implications to think about:

https://github.com/SwiftDocOrg/swift-doc/blob/a2013b64ffbcf91be45e6ecff9e88fdf8019a08d/Assets/css/all.css#L890

**Comment by mattt** [comment] 2020-05-27 19:26
Ah, this looks like a regression related to #114.

**Comment by mattt** [comment] 2020-07-27 18:13
Fixed by #144. Thanks again for your help with this, @mbrandonw!

**Closed by mattt** 2020-07-27 18:13 UTC
Labels: bug, design
