### ISSUE TITLE
Sidebar links are broken in the HTML version

### ISSUE THREAD

**Issue by victor-pavlychko** [SwiftDocOrg/swift-doc#82] opened 2020-04-13 23:08 UTC
All sidebar navigational links point to the root document. Looks like this is caused by the `<base href="\#(baseURL)"/>` element.

**Comment by mattt** [comment] 2020-04-13 23:18
Yeah, this is something @kean pointed out in a recent thread (still catching up from the weekend, sorry!) 

This behavior of base tags surprised me – I didn’t know about this behavior before. In light of this new information, I think we should consider the alternative approach discussed in #65, which was to factor the base URL into the path helper.

**Comment by kean** [comment] 2020-04-14 22:18
My bad, I misunderstood how <base> works. It applies not just to relative URLs, but also anchors https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base. I use absolute paths on my Jekyll site. It is convenient when this parameter available globally so every page you generate has access to it.

**Comment by mattt** [comment] 2020-04-16 12:18
@kean Same here wrt/Jekyll and absolute paths. My suggestion to use a `<base>` tag was out of left field, and a bad call on my part. The good news is that we haven't released a new version with that yet, so we can make this change without worrying about backwards compatibility.

**Comment by dsmurfin** [comment] 2020-04-22 11:30
I think this is also the same issue in the CommonMark version.

![Screenshot 2020-04-22 at 12 29 52](https://user-images.githubusercontent.com/4533485/79976772-12e1c180-8495-11ea-901b-fdb32303bb7b.png)

**Comment by mattt** [comment] 2020-04-24 19:20
@dsmurfin That is indeed the cause. I'll prioritize a fix for this work to get that out later today.

**Comment by mattt** [comment] 2020-05-13 15:13
This is fixed by #93.

**Closed by mattt** 2020-05-13 15:13 UTC
