### ISSUE TITLE
Fatal error: could not load resource bundle

### ISSUE THREAD

**Issue by vishcshah** [SwiftDocOrg/swift-doc#196] opened 2020-10-02 14:14 UTC
While generating format html with the current latest version getting Illegal instruction: 4.

Using latest Xcode Version 12.0.1 (12A7300)
swift-doc version: 1.0.0-beta.5

**this is my command:**
swift-doc generate somePath --module-name testing --output public --format html

Error:
Fatal error: could not load resource bundle: /usr/local/bin/swift-doc_swift-doc.bundle: file swift_doc/resource_bundle_accessor.swift, line 7
Illegal instruction: 4

Let me know if I am missing something.

**Comment by MattKiazyk** [comment] 2020-10-02 16:11
Getting the same thing as well. 

Installed beta-5 via homebrew.

**Comment by mattt** [comment] 2020-10-04 13:18
Really sorry for the inconvenience. This is a consequence of unexpected behavior in Swift package resources (`Bundle.module`), added by #192. I just reverted and am in the process of creating a new release.

**Comment by mattt** [comment] 2020-10-04 15:13
@vishcshah @MattKiazyk I want to add some end-to-end testing before doing any more releases, which will take a few days. In the meantime, please downgrade to 1.0.0-beta.4 or reinstall manually from the latest head of master

**Comment by mattt** [comment] 2020-10-06 20:09
@vishcshah @MattKiazyk @MaxDesiatov  I think I figured out what was causing this release to fail. The good news is that the problem appears to be how it's distributed with Homebrew (rather than the project itself), so updating the formula should fix this release. Could you please try reinstalling with the following commands?

```terminal
$ brew uninstall swift-doc
$ brew untap swiftdocorg/formulae # in case you tapped our formula repo
$ brew install swiftdocorg/formulae/swift-doc
```

**Comment by MaxDesiatov** [comment] 2020-10-06 20:23
After reinstalling the formula with the steps you've listed I no longer get #197.

But now I get the exact same error as the OP:

```
% swift doc generate --module-name JavaScriptKit --format html Sources
Fatal error: could not load resource bundle: /usr/local/bin/swift-doc_swift-doc.bundle: file swift_doc/resource_bundle_accessor.swift, line 7
zsh: illegal hardware instruction  swift doc generate --module-name JavaScriptKit --format html Sources
```

**Comment by mattt** [comment] 2020-10-06 20:32
@MaxDesiatov Thanks. I didn't expect this to fix #197 (I'm working on a solution to that now). Could you share the output when you run the following commands?

```terminal
$ swift-doc --version
$ tree /usr/local/Cellar/swift-doc/
```

**Comment by MaxDesiatov** [comment] 2020-10-06 20:48
```
% swift-doc --version
1.0.0-beta.5
% tree /usr/local/Cellar/swift-doc/
zsh: command not found: tree
% ls -R /usr/local/Cellar/swift-doc/    
1.0.0-beta.5/

/usr/local/Cellar/swift-doc//1.0.0-beta.5:
Changelog.md          INSTALL_RECEIPT.json  LICENSE.md            README.md             bin/                  libexec/

/usr/local/Cellar/swift-doc//1.0.0-beta.5/bin:
swift-doc@

/usr/local/Cellar/swift-doc//1.0.0-beta.5/libexec:
swift-doc*                  swift-doc_swift-doc.bundle/

/usr/local/Cellar/swift-doc//1.0.0-beta.5/libexec/swift-doc_swift-doc.bundle:
Resources/

/usr/local/Cellar/swift-doc//1.0.0-beta.5/libexec/swift-doc_swift-doc.bundle/Resources:
all.min.css
```

**Comment by mattt** [comment] 2020-10-06 21:00
> You mean `tree` from `brew install tree`, right?

Yep. (Huh, I could've sworn that was a built-in...)

Thanks for sharing this, @MaxDesiatov. This is indeed what I was going for with the formula:

- The executable (`swift-doc`) and resource bundle (`swift-doc_swift-doc.bundle`) in `libexec`
- A symlink from `libexec/swift-doc` to `bin/swift-doc`

My hope was that the symlink would allow `swift-doc` to find its resource bundle without exposing that bundle to the user's `PATH`. It seems to work on my machine (™), but I'm trying now to reproduce on my secondary.

**Comment by mattt** [comment] 2020-10-06 22:15
@MaxDesiatov Figured it out. Turns out what I wanted wasn't an alias / symbolic link, but instead a shim. I updated the formula accordingly. I just reinstalled locally and it seems to be working as expected. Feel free to give it a go and let me know how it's working for you.

**Comment by mattt** [comment] 2020-10-07 08:18
@MattKiazyk @vishcshah This should now be fixed with the latest Homebrew formula. Please try reinstalling with the following commands to verify the fix:

```terminal
$ brew uninstall swift-doc
$ brew untap swiftdocorg/formulae # in case you tapped our formula repo
$ brew install swiftdocorg/formulae/swift-doc
```

**Comment by MaxDesiatov** [comment] 2020-10-07 08:38
The installation now fails for me with this error:

```
Error: An exception occurred within a child process:
  Errno::EPERM: Operation not permitted @ rb_file_s_rename - (/Applications/Xcode-12.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/lib_InternalSwiftSyntaxParser.dylib, /usr/local/Cellar/swift-doc/1.0.0-beta.5/lib/lib_InternalSwiftSyntaxParser.dylib)
```

**Comment by MaxDesiatov** [comment] 2020-10-07 08:57
Would it make sense to create another end-to-end test that verifies that `swift-doc` can installed via Homebrew and works well after installation?

**Comment by mattt** [comment] 2020-10-07 09:40
> The installation now fails for me with this error:
> 
> ```
> Error: An exception occurred within a child process:
>   Errno::EPERM: Operation not permitted @ rb_file_s_rename - 
> (/Applications/Xcode-12.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/lib_InternalSwiftSyntaxParser.dylib,
>  /usr/local/Cellar/swift-doc/1.0.0-beta.5/lib/lib_InternalSwiftSyntaxParser.dylib)
> ```

Sorry, that's me debugging something else related to #197. It's baffling and endlessly frustrating to me that there doesn't appear to be a way to try out Homebrew formulas locally.

> Would it make sense to create another end-to-end test that verifies that swift-doc can be installed via Homebrew and works well after the installation?

Indeed it would. That should be a separate action workflow that runs on a cron schedule, since it depends on so many different factors (swift-doc, the formula, Homebrew itself, Xcode, macOS).

**Comment by MaxDesiatov** [comment] 2020-10-07 09:42
>doesn't appear to be a way to try out Homebrew formulas locally

You can pass a path to a formula on you local storage like `brew install ../homebrew-tap/swift-doc.rb`.

**Comment by mattt** [comment] 2020-10-07 09:54
> > doesn't appear to be a way to try out Homebrew formulas locally
> 
> You can pass a path to a formula on you local storage like `brew install ../homebrew-tap/swift-doc.rb`.

🤦 

I swear this wasn't working when I tried that yesterday (I have the Terminal logs to prove it!). Anyway, very glad to have that option available.

**Comment by MaxDesiatov** [comment] 2020-10-07 09:55
Thanks to Homebrew, there's a lot for all of us to learn 😄

**Comment by mattt** [comment] 2020-10-07 10:01
@MaxDesiatov I was pleasantly surprised to see that Homebrew has some sophisticated tooling built for doing this kind of thing — specifically, https://github.com/Homebrew/ruby-macho. No shelling out to `otool` or `install_name_tool`! 

Here's the relevant change in the formula (more or less):

```ruby
macho = MachO.open(buildpath/"release/swift-doc")
if (toolchain = macho.rpaths.find { |path| path.include?(".xctoolchain") })
  cp Dir["#{toolchain}/*.dylib"], lib, verbose: true
  macho.change_rpath toolchain, lib
  macho.write!
end
```

That, in theory, should address #197 

Once that's working, the last thing I want to do is add a bottle (pre-built binary), and then I'll be done futzing with that for a while.

**Comment by MaxDesiatov** [comment] 2020-10-07 10:04
>What works?
>
>    Reading data from x86/x86_64/PPC Mach-O files

This will break on Apple Silicon I'm afraid 😧

**Comment by mattt** [comment] 2020-10-07 10:08
> > What works?
> > Reading data from x86/x86_64/PPC Mach-O files
> 
> This will break on Apple Silicon I'm afraid 😧

😂 

According to the Apple event countdown timer, we have another 6 days and 6 hours until we need to worry about that. #yolo

**Comment by MaxDesiatov** [comment] 2020-10-07 12:48
I've just tried the updated formula, it works for me. Thanks for the fix @mattt!

**Comment by mattt** [comment] 2020-10-07 17:43
Excellent. Thank you for verifying. Botching a release feels bad, but I really like where we are now. I'm just finishing up [a GitHub Action](https://github.com/NSHipster/update-homebrew-formula-action) to automate this going forward. I also filed #202 to track additional work on end-to-end testing.

@vishcshah Please let me know if you're still having this problem, and I'd be happy to reopen and help troubleshoot it with you.

**Closed by mattt** 2020-10-07 17:43 UTC
Labels: bug

**Comment by vishcshah** [comment] 2020-10-08 10:29
@mattt I will try in 2 or 3 days, will let you know about the results.
